# Generated by Django 6.0.6 on 2026-06-25 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categorias", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pelicula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("anio_creacion", models.IntegerField()),
                ("descripcion", models.TextField()),
                ("poster", models.ImageField(upload_to="peliculas/imagenes")),
                ("estado", models.BooleanField(default=False)),
                (
                    "categoria",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="categorias.categoria",
                    ),
                ),
            ],
        ),
    ]
