# Generated by Django 6.0.6 on 2026-06-25 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("peliculas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mensaje", models.TextField()),
                ("fecha_mensaje", models.DateTimeField(auto_now_add=True)),
                ("estado", models.BooleanField(default=False)),
                (
                    "pelicula",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="peliculas.pelicula",
                    ),
                ),
            ],
        ),
    ]
