# Generated by Django 6.0.6 on 2026-06-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genero", models.CharField(max_length=100)),
                ("slug", models.SlugField()),
            ],
        ),
    ]
