# Generated by Django 6.0.6 on 2026-06-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categorias", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
